apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: rupa787/nodejsapp-1.0:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000


---

apiVersion: v1 
kind: Service 
metadata: 
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: "TCP"
      port: 80 
      targetPort: 3000 
  type: LoadBalancer 
