# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      deployment: blue
  template:
    metadata:
      labels:
        app: nodejs-app
        deployment: blue
    spec:
      containers:
      - name: nodejs-app
        image: rupa787/nodejsapp-1.0:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-green
spec:
  replicas: 0 # Initially, set to 0
  selector:
    matchLabels:
      app: nodejs-app
      deployment: green
  template:
    metadata:
      labels:
        app: nodejs-app
        deployment: green
    spec:
      containers:
      - name: nodejs-app
        image: rupa787/nodejsapp-1.0:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
