apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels: 
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: rupa787/nodejsapp-1.0:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
